### ISSUE TITLE
InvalidOperationException: The property 'UserId' on entity type 'User_Answers' has a temporary value. Either set a permanent value explicitly or ensure that the database is configured to generate values for this property.

### ISSUE THREAD

**Issue by nurgi17** [nurgi17/SWD6.NET#1]
@nightBaker 
<img width="1440" alt="Снимок экрана 2019-11-16 в 10 55 07" src="https://user-images.githubusercontent.com/28563673/68988324-93095880-085f-11ea-8e1e-56ae2140579a.png">

**Comment by nightBaker** [comment]
If we go to chrome console and look on request 
![image](https://user-images.githubusercontent.com/10187750/69034339-2df26600-0a0b-11ea-8974-bd49654a4fa3.png)
We can see that body of the request contains following parameters
**Answer**: 1123
**__RequestVerificationToken**: CfDJ8MxtTh2dBW9OsgwiuwWkzfmhC1FpSYaNzCws_1Emgcggqzl00guRTFrpFciOyiEwEbrfofjMeuBwgVu0vRC-CdZsvOsdDaTJSYQH3WTpZwIA3M0K6MV_9pbMlInKH1rS33Ubag7dqACFk3r6FpGJ61Q

So there are no **UserId, SurveyId**. The reason is your inputs are **disabled**
![image](https://user-images.githubusercontent.com/10187750/69034482-84f83b00-0a0b-11ea-902d-10bbaee98d61.png)

By default disabled inputs are not sent to the server. So in server side, especialy in controller we do not have values 
![image](https://user-images.githubusercontent.com/10187750/69034597-d4d70200-0a0b-11ea-8258-8c22cd4d4cd0.png)

You can use hidden inputs instead disabled
